import {z} from 'zod';import {chatRequestSchema} from './providers/openai-chat.js';import {ModelSession} from './session.js';import {canonicalChatHash} from './recordings.js';import type {ResolvedLlmPolicy,ModelSelection,ModelCall,ChatRequest} from './types.js';import {HarnessError} from '../security/errors.js';import {sha256} from '../spec/load.js';
export interface ModelGatewayConfig {policy:ResolvedLlmPolicy;selection?:ModelSelection;routes:Array<{path:string;nodeId:string}>;sourceHash:string;fixtureHash:string;caseTimeoutMs?:number;replayCalls?:Array<{requestHash:string;responseHash:string;response:unknown}>;}
const rawSchema=z.strictObject({model:z.string().max(256),messages:z.array(z.unknown()),stream:z.literal(false).optional(),response_format:z.unknown().optional(),temperature:z.number().nullable().optional(),seed:z.number().nullable().optional(),max_tokens:z.number().nullable().optional(),max_completion_tokens:z.number().nullable().optional(),top_p:z.number().nullable().optional(),frequency_penalty:z.number().nullable().optional(),presence_penalty:z.number().nullable().optional(),n:z.literal(1).nullable().optional(),logprobs:z.boolean().nullable().optional(),stop:z.union([z.string(),z.array(z.string()),z.null()]).optional()});
export function normalizeChatBody(raw:unknown):ChatRequest{const parsed=rawSchema.parse(raw);if(parsed.stop!=null||parsed.top_p!=null&&parsed.top_p!==1||parsed.frequency_penalty!=null&&parsed.frequency_penalty!==0||parsed.presence_penalty!=null&&parsed.presence_penalty!==0||parsed.logprobs===true)throw new HarnessError('UNSUPPORTED','Unsupported non-default model controls are never discarded');return chatRequestSchema.parse({messages:parsed.messages,...(parsed.response_format?{responseFormat:parsed.response_format}:{})});}
export class GatewayModels {
 readonly calls:ModelCall[]=[];private session?:ModelSession;private index=0;
 constructor(readonly config:ModelGatewayConfig){if(config.policy.mode==='local')this.session=new ModelSession(config.policy,config.selection);}
 route(path:string){return this.config.routes.find(r=>r.path===path);}
 async respond(path:string,body:unknown,signal:AbortSignal){const route=this.route(path);if(!route)throw new HarnessError('CONFIG','Unknown model route is never forwarded');const request=normalizeChatBody(body);if(++this.index>this.config.policy.maxCalls)throw new HarnessError('QUOTA','Per-case model call quota exceeded');const start=Date.now();if(this.config.policy.mode==='local'){try{return await this.session!.invoke(request,{purpose:'workflow',nodeId:route.nodeId},signal);}finally{this.calls.splice(0,this.calls.length,...this.session!.calls);}}
 if(this.config.policy.mode==='replay'){const stored=this.config.replayCalls?.[this.index-1];if(!stored||stored.requestHash!==canonicalChatHash(request)||stored.responseHash!==sha256(JSON.stringify(stored.response)))throw new HarnessError('EVIDENCE','Replay response is missing/exhausted or does not match request');this.calls.push({purpose:'workflow',nodeId:route.nodeId,mode:'replay',status:'success',requestHash:stored.requestHash,responseHash:stored.responseHash,response:stored.response,durationMs:Date.now()-start,selection:this.config.selection,settings:this.config.policy.settings});return stored.response;}
 throw new HarnessError('CONFIG','Mock responses are supplied only by explicit ordered fixture rules');}
 recordMock(path:string,body:unknown,response:unknown){const route=this.route(path);if(!route)return;const request=normalizeChatBody(body);if(++this.index>this.config.policy.maxCalls)throw new HarnessError('QUOTA','Per-case model call quota exceeded');this.calls.push({purpose:'workflow',nodeId:route.nodeId,mode:'mock',status:'success',requestHash:canonicalChatHash(request),responseHash:sha256(JSON.stringify(response)),response,durationMs:0});}
}
