import {canonical,canonicalChatHash} from './canonical.js';
import {readFile,writeFile,mkdir,realpath,stat} from 'node:fs/promises';import {dirname,resolve,basename} from 'node:path';import {createHash} from 'node:crypto';import {z} from 'zod';import {isWithinDirectory,sha256} from '../spec/load.js';import type {ChatRequest,ModelSelection,GenerationSettings} from './types.js';import {chatRequestSchema} from './providers/openai-chat.js';import {generationSchema} from './client.js';import {HarnessError} from '../security/errors.js';
const hash=z.string().regex(/^[a-f0-9]{64}$/);const selection=z.strictObject({endpoint:z.string().url(),model:z.string(),digest:hash,runtimeVersion:z.string(),capabilities:z.array(z.string()),remote:z.literal(false),provider:z.enum(['ollama','openai-compatible']).optional(),contextBudgetField:z.enum(['context_tokens','num_ctx']).optional()});
const schema=z.strictObject({formatVersion:z.literal(1),protocol:z.literal('openai-chat'),sourceHash:hash,fixtureHash:hash,selection,settings:generationSchema,calls:z.array(z.strictObject({requestHash:hash,responseHash:hash,response:z.json()})).min(1).max(20)});
export interface Recording {formatVersion:1;protocol:'openai-chat';sourceHash:string;fixtureHash:string;selection:ModelSelection;settings:GenerationSettings;calls:Array<{requestHash:string;responseHash:string;response:unknown}>;}
export interface ReplayIdentity {approvedHash:string;sourceHash:string;fixtureHash:string;selection?:ModelSelection;settings?:GenerationSettings;}
export {canonicalChatHash} from './canonical.js';
async function checkPath(path:string,root:string,create=false){const base=await realpath(root),target=resolve(path);if(!isWithinDirectory(resolve(root),target)&&!isWithinDirectory(base,target))throw new HarnessError('CONFIG','Recording path escapes project');if(create){let ancestor=dirname(target);while(true){try{const current=await realpath(ancestor);if(!isWithinDirectory(base,current))throw new HarnessError('CONFIG','Recording ancestor escapes project');break;}catch(error:any){if(error.code!=='ENOENT')throw error;const next=dirname(ancestor);if(next===ancestor)throw new HarnessError('CONFIG','Recording ancestor unavailable');ancestor=next;}}await mkdir(dirname(target),{recursive:true,mode:0o700});}const parent=await realpath(dirname(target));if(!isWithinDirectory(base,parent))throw new HarnessError('CONFIG','Recording parent escapes project');return resolve(parent,basename(target));}
export async function writeRecording(path:string,recording:Recording,projectRoot=process.cwd()):Promise<string>{const data=schema.parse(recording);const text=JSON.stringify(data,null,2)+'\n';if(Buffer.byteLength(text)>1024*1024)throw new HarnessError('CONFIG','Recording exceeds 1 MiB');const target=await checkPath(path,projectRoot,true);await writeFile(target,text,{mode:0o600,flag:'wx'});return sha256(text);}
export async function readReplay(path:string,identity:ReplayIdentity,request:ChatRequest,index:number,projectRoot=process.cwd()):Promise<unknown>{const target=await checkPath(path,projectRoot);const actual=await realpath(target),base=await realpath(projectRoot);if(!isWithinDirectory(base,actual)||(await stat(actual)).size>1024*1024)throw new HarnessError('CONFIG','Recording escapes project or exceeds limit');const text=await readFile(actual,'utf8');if(sha256(text)!==identity.approvedHash)throw new HarnessError('CONFIG','Recording approval hash does not match');const r=schema.parse(JSON.parse(text));if(r.sourceHash!==identity.sourceHash||r.fixtureHash!==identity.fixtureHash||identity.selection&&JSON.stringify(canonical(r.selection))!==JSON.stringify(canonical(identity.selection))||identity.settings&&JSON.stringify(canonical(r.settings))!==JSON.stringify(canonical(identity.settings)))throw new HarnessError('CONFIG','Recording identity does not match source/fixture/model/settings');const call=r.calls[index];if(!call)throw new HarnessError('EVIDENCE','Replay response sequence exhausted');if(call.requestHash!==canonicalChatHash(request)||call.responseHash!==sha256(JSON.stringify(call.response)))throw new HarnessError('EVIDENCE','Replay request/response hash does not match');return call.response;}

export async function approvedRecording(path:string,identity:ReplayIdentity,projectRoot=process.cwd()):Promise<Recording>{const target=await checkPath(path,projectRoot);const actual=await realpath(target);if(!isWithinDirectory(await realpath(projectRoot),actual)||(await stat(actual)).size>1024*1024)throw new HarnessError('CONFIG','Recording path/size invalid');const text=await readFile(actual,'utf8');if(sha256(text)!==identity.approvedHash)throw new HarnessError('CONFIG','Recording approval hash does not match');const r=schema.parse(JSON.parse(text));if(r.sourceHash!==identity.sourceHash||r.fixtureHash!==identity.fixtureHash||identity.settings&&JSON.stringify(canonical(r.settings))!==JSON.stringify(canonical(identity.settings)))throw new HarnessError('CONFIG','Recording identity does not match');return r as Recording;}
