import {reconcileDisposedState} from '../adapters/docker/disposal.js';
import {proveContainment} from '../adapters/docker/containment.js';
import {RuntimeLifetime} from './lifetime.js';
import {randomUUID,randomBytes} from 'node:crypto';import {cp,mkdir,readFile,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {fileURLToPath} from 'node:url';
import {HarnessError,errorMessage} from '../security/errors.js';import {ResourceJournal} from './journal.js';import {N8nApiAdapter} from '../adapters/n8n-api/index.js';
import {Manifest} from './manifest.js';import {N8nCloudAdapter} from '../adapters/n8n-cloud/index.js';import {CloudClient} from '../adapters/n8n-cloud/client.js';import {DockerEngine,containerArguments} from '../adapters/docker/engine.js';import {GeneratedEnvironment} from '../adapters/docker/environment.js';import {bootstrap,waitForApi} from '../adapters/docker/bootstrap.js';import {selectImages,type ImageSet} from '../adapters/docker/images.js';import {createOwned,recoverOwned} from '../adapters/n8n-api/resources.js';import {ownedLoopbackClient} from '../adapters/n8n-api/client.js';import {DockerGateway} from '../gateway/docker.js';import {Gateway} from '../gateway/server.js';import type {GatewayTransport} from '../gateway/transport.js';import type {RuntimeAdapter} from './types.js';
export interface RuntimeCapabilities {kind:'cloud'|'docker';version?:string;imageDigest?:string;triggerKinds:Array<'webhook-json'|'form-file'>;nodeCatalogHash?:string;operations:string[];containment?:'unqualified'|'verified';}
export interface RuntimeOptions {runtime:'cloud'|'docker';stateDirectory:string;baseUrl?:string;apiKey?:string;pins?:ImageSet;startupTimeoutMs?:number;keepOnFailure?:boolean;}
export interface RuntimeSession {adapter:RuntimeAdapter;gateway:GatewayTransport;gatewayUrl:string;capabilities:RuntimeCapabilities;journal:ResourceJournal;close(failed?:boolean):Promise<void>;}
export async function createRuntime(o:RuntimeOptions,signal:AbortSignal):Promise<RuntimeSession>{
 if(!['cloud','docker'].includes(o.runtime))throw new HarnessError('CONFIG','Unknown runtime');if(signal.aborted)throw new HarnessError('INTERRUPTED','Runtime startup interrupted');const runId=randomUUID().replaceAll('-','');
 if(o.runtime==='cloud'){if(!o.baseUrl||!o.apiKey)throw new HarnessError('CONFIG','Cloud origin and private API key are required');const client=new CloudClient(o.baseUrl,o.apiKey),journal=new ResourceJournal(o.stateDirectory,runId,client.baseUrl),adapter=new N8nCloudAdapter(client,new Manifest(o.stateDirectory,runId,client.baseUrl)),gateway=new Gateway();return {adapter,gateway,gatewayUrl:'',journal,capabilities:{kind:'cloud',triggerKinds:['webhook-json'],operations:[]},close:async()=>{await gateway.close();}};}
 const engine=new DockerEngine(),owner=await engine.identity(),journal=new ResourceJournal(o.stateDirectory,runId,owner);const startup=AbortSignal.any([signal,AbortSignal.timeout(o.startupTimeoutMs??180000)]);const envFiles:GeneratedEnvironment[]=[];let gateway:DockerGateway|undefined;let apiAdapter:N8nApiAdapter|undefined;
 const lifetime=new RuntimeLifetime(async()=>{await apiAdapter?.settlePreparations();await gateway?.close().catch(()=>{});const recovery=await recoverOwned(journal,owner,{remove:async e=>{if(['workflow','execution','credential','table'].includes(e.kind)){if(!apiAdapter)throw new HarnessError('CLEANUP','API recovery adapter unavailable');await apiAdapter.removeResource(e);}else await engine.remove(e);}});await reconcileDisposedState(journal,engine);for(const f of envFiles)await f.dispose().catch(()=>{});if(journal.leftovers().length)throw new HarnessError('CLEANUP',`Runtime journal ${journal.path} retains ${journal.leftovers().length} resources/intents`);},o.keepOnFailure??false,journal.path,()=>gateway?.detach());const close=(failed=false)=>lifetime.close(failed);
 try{
  const instance=await bootstrap({stateDirectory:o.stateDirectory,journal,engine,pins:o.pins},startup),pins=selectImages(await engine.architecture(),o.pins);const stem='wfcheck-'+runId;
  // Replace the initialization server with its external-runner configuration.
  const initial=journal.leftovers().find(e=>e.id===instance.containerId)!;await engine.exec(['stop',initial.id!],startup);await engine.remove(initial);await journal.markCleaned(initial.intentId);
  const brokerToken=randomBytes(32).toString('hex');const serverEnv=await GeneratedEnvironment.create(o.stateDirectory,runId,'server',{N8N_DIAGNOSTICS_ENABLED:'false',N8N_VERSION_NOTIFICATIONS_ENABLED:'false',N8N_PERSONALIZATION_ENABLED:'false',N8N_BLOCK_ENV_ACCESS_IN_NODE:'true',N8N_RUNNERS_ENABLED:'true',N8N_RUNNERS_MODE:'external',N8N_RUNNERS_BROKER_LISTEN_ADDRESS:'0.0.0.0',N8N_RUNNERS_AUTH_TOKEN:brokerToken,NODE_FUNCTION_ALLOW_BUILTIN:'crypto',N8N_LOG_LEVEL:'error',N8N_DEFAULT_BINARY_DATA_MODE:'filesystem'});envFiles.push(serverEnv);
  const own=async(kind:'container'|'network',name:string,args:string[])=>createOwned(journal,{kind,name},async()=>({name,id:await engine.exec(args,startup)}));
  const server=await own('container',stem+'-n8n',containerArguments({name:stem+'-n8n',runId,image:pins.n8n,network:instance.networkId,volume:instance.volumeId,envFile:serverEnv,readOnly:true,cache:true}));await engine.exec(['start',server.id!],startup);
  const runnerEnv=await GeneratedEnvironment.create(o.stateDirectory,runId,'runner',{N8N_RUNNERS_TASK_BROKER_URI:'http://'+stem+'-n8n:5679',N8N_RUNNERS_AUTH_TOKEN:brokerToken,N8N_RUNNERS_MAX_CONCURRENCY:'1',N8N_RUNNERS_TASK_TIMEOUT:'120',NODE_FUNCTION_ALLOW_BUILTIN:'crypto'});envFiles.push(runnerEnv);
  const runner=await own('container',stem+'-runner',containerArguments({name:stem+'-runner',runId,image:pins.runner,network:instance.networkId,envFile:runnerEnv,readOnly:true,cpus:1,memory:'1g'}));await engine.exec(['start',runner.id!],startup);
  const context=join(o.stateDirectory,'runtime-'+runId+'-build');await mkdir(context,{recursive:true,mode:0o700});const pkg=fileURLToPath(new URL('../../',import.meta.url));await cp(join(pkg,'package.json'),join(context,'package.json'));await cp(join(pkg,'docker/runtime-package-lock.json'),join(context,'package-lock.json'));await cp(join(pkg,'dist'),join(context,'dist'),{recursive:true});await writeFile(join(context,'Dockerfile'),await readFile(join(pkg,'docker/gateway.Dockerfile')));
  await engine.exec(['build','--quiet','--build-arg','NODE_IMAGE='+pins.gatewayBase,'--iidfile',join(context,'image-id'),'--label','wfcheck.gateway=managed',context],startup);const image=(await readFile(join(context,'image-id'),'utf8')).trim();await rm(context,{recursive:true,force:true});
  const uplink=await own('network',stem+'-uplink',['network','create','--label','wfcheck.run='+runId,stem+'-uplink']);
  const gateEnv=await GeneratedEnvironment.create(o.stateDirectory,runId,'gateway',{WFCHECK_N8N_HOST:stem+'-n8n',WFCHECK_KEEP_ON_DISCONNECT:String(o.keepOnFailure??false)});envFiles.push(gateEnv);
  const gate=await own('container',stem+'-gateway',[...containerArguments({name:stem+'-gateway',runId,image,network:instance.networkId,envFile:gateEnv,publish:true,readOnly:true,cpus:1,memory:'256m'}).slice(0,-1),'-i',image]);await engine.exec(['network','connect',uplink.id!,gate.id!],startup);gateway=new DockerGateway(gate.id!);await gateway.ready();
  const ports=JSON.parse(await engine.exec(['inspect','--format','{{json .NetworkSettings.Ports}}',gate.id!],startup));const bindings=ports['5678/tcp'];if(bindings?.length!==1||bindings[0].HostIp!=='127.0.0.1'||!bindings[0].HostPort)throw new HarnessError('CAPABILITY','Loopback ingress was not confirmed');
  const origin='http://127.0.0.1:'+bindings[0].HostPort;
  const client=instance.client.loopback(origin,journal,gate.id!);await waitForApi(client,startup);
  const manifest=new Manifest(o.stateDirectory,runId,client.baseUrl),adapter=new N8nApiAdapter(client,manifest,journal,{managedDocker:true,parentId:instance.volumeId,credentialReader:async id=>{const file='/home/node/.n8n/credential-check-'+randomUUID()+'.json';await engine.exec(['exec',server.id!,'n8n','export:credentials','--id='+id,'--output='+file]);const code="const fs=require('fs'),p=JSON.parse(fs.readFileSync(0,'utf8')).file;try{const rows=JSON.parse(fs.readFileSync(p));if(rows.length!==1)throw Error();console.log(JSON.stringify({id:rows[0].id,name:rows[0].name}));}finally{fs.unlinkSync(p);}";return JSON.parse(await engine.exec(['exec','-i',server.id!,'node','-e',code],undefined,JSON.stringify({file})));}});apiAdapter=adapter;
  await adapter.doctor();await proveContainment(engine,[server.id!,runner.id!],startup);
  lifetime.watch(signal);
  return {adapter,gateway,gatewayUrl:'http://'+stem+'-gateway:43199',journal,capabilities:{kind:'docker',version:instance.version,imageDigest:instance.imageDigest,nodeCatalogHash:instance.catalog.sha256,triggerKinds:['webhook-json','form-file'],operations:['public-api','external-runner'],containment:'verified'},close};
 }catch(error){try{await close();}catch(cleanup){throw new HarnessError('CLEANUP',`Startup failed (${errorMessage(error)}); ${errorMessage(cleanup)}`);}throw error;}
}
