import {analyzeWorkflow} from '../analysis/index.js';
import {sha256} from '../spec/load.js';
import {resolveModel} from '../llm/resolve.js';
import {approvedRecording,writeRecording} from '../llm/recordings.js';
import type {ModelGatewayConfig} from '../llm/gateway.js';
import {resolveLlmPolicy} from '../llm/policy.js';
import type {ResolvedLlmPolicy,LlmOverrides} from '../llm/types.js';
import {randomUUID} from 'node:crypto';import {resolve,relative} from 'node:path';import type {NormalizedSuite,NormalizedTest} from '../spec/normalized.js';import {readBounded} from '../spec/load.js';import {loadInput} from './inputs.js';import type {CompiledInput,RuntimeAdapter,RuntimeHandle,TriggerAttempt,Evidence} from './types.js';import {prepareV2Workflow} from '../security/bindings.js';import {prepareWorkflow} from '../security/workflow.js';import {HarnessError,errorMessage} from '../security/errors.js';import type {GatewayTransport} from '../gateway/transport.js';import type {TestResult,SuiteResult} from './runner.js';import {evaluate} from '../assertions/index.js';import {redactor} from '../security/redact.js';
export interface CompiledTestV2 {spec:NormalizedTest;source:string;input:CompiledInput;sourceSchemaVersion:1|2;llm:ResolvedLlmPolicy;modelConfig?:ModelGatewayConfig;}
export async function compileSuiteV2(suite:NormalizedSuite,base:string,projectRoot=process.cwd(),llmOverrides:LlmOverrides={}):Promise<CompiledTestV2[]>{redactor.add(...suite.redactValues);const tests:CompiledTestV2[]=[];for(const spec of suite.tests){const source=await readBounded(resolve(base,spec.workflow),projectRoot),input=await loadInput({...spec.input,fixture:relative(projectRoot,resolve(base,spec.input.fixture))},projectRoot);if(input.kind==='file'&&input.mimeType.startsWith('image/')&&spec.bindings.some(b=>b.protocol==='openai-chat')&&Math.ceil(input.bytes.length/3)*4+4096>65536)throw new HarnessError('CONFIG','Inline image exceeds the 64 KiB model request budget');const p=suite.sourceSchemaVersion===1?prepareWorkflow(source,'https://mock.test/r/preflight/'+spec.id,'preflight',spec.id,'preflight-token',spec.timeoutMs):prepareV2Workflow(source,spec,'https://mock.test/r/preflight/'+spec.id,'preflight',spec.id,'preflight-token');const ids=new Set(p.workflow.nodes.map(n=>n.id));for(const a of spec.assertions)if('nodeId'in a&&!ids.has(a.nodeId))throw new HarnessError('CONFIG','Assertion references an unknown node');tests.push({spec,source,input,sourceSchemaVersion:suite.sourceSchemaVersion,llm:resolveLlmPolicy(llmOverrides,spec.llm,suite.llm)});}return tests;}
export async function prepareModelSelections(compiled:CompiledTestV2[],signal:AbortSignal){for(const t of compiled){const workflow=JSON.parse(t.source),routes=[...t.spec.bindings.filter(b=>b.protocol==='openai-chat').map(b=>({path:b.mockPath,nodeId:b.nodeId})),...workflow.nodes.filter((n:any)=>n.type==='@n8n/n8n-nodes-langchain.lmChatOpenAi').map((n:any)=>({path:'/native-model/'+n.id+'/v1/chat/completions',nodeId:n.id}))];if(!routes.length)continue;const policy=t.llm??resolveLlmPolicy();const selection=await resolveModel(policy,t.input.kind==='file'&&t.input.mimeType.startsWith('image/')?['completion','vision']:['completion'],signal);const config:ModelGatewayConfig={policy,selection,routes,sourceHash:(await import('../spec/load.js')).sha256(t.source),fixtureHash:t.input.sha256,caseTimeoutMs:t.spec.timeoutMs};if(policy.mode==='replay'){if(!policy.replayHash||!policy.replay)throw new HarnessError('CONFIG','Replay needs an independently approved recording hash');const recording=await approvedRecording(policy.replay,{approvedHash:policy.replayHash,sourceHash:config.sourceHash,fixtureHash:config.fixtureHash,settings:policy.settings});if(policy.model!=='auto'&&policy.model!==recording.selection.model)throw new HarnessError('CONFIG','Replay model identity changed');config.selection=recording.selection;config.replayCalls=recording.calls;}t.modelConfig=config;}}
export async function runCompiledV2(suite:NormalizedSuite,compiled:CompiledTestV2[],adapter:RuntimeAdapter & {recover?:(testId?:string)=>Promise<void>;tables?:(h:RuntimeHandle,signal:AbortSignal)=>Promise<import('./types.js').TableEvidence[]>},gateway:GatewayTransport,url:string,runId:string,signal:AbortSignal,onResult?:(t:TestResult)=>void,runtime?:import('./factory.js').RuntimeCapabilities):Promise<SuiteResult>{
 if(!compiled.length||compiled.length>20)throw new HarnessError('CONFIG','Suite must plan 1-20 serial executions');const start=Date.now(),results:TestResult[]=[];let halted=false;
 for(const test of compiled){const began=Date.now(),r:TestResult={id:test.spec.id,verificationKind:test.spec.verificationKind,status:'error',durationMs:0,assertions:[],fixtureHash:test.input.sha256,cleanup:{status:'not-created'}};let handle:RuntimeHandle|undefined;
 try{if(halted||signal.aborted)throw new HarnessError('INTERRUPTED','Case not executed after infrastructure error or interruption');const registration=await gateway.register(runId,test.spec.id,test.spec.mocks,test.spec.timeoutMs+30000,test.modelConfig);redactor.add(registration.token,registration.token.slice(0,24));const prepared=test.sourceSchemaVersion===1?prepareWorkflow(test.source,url+'/r/'+runId+'/'+test.spec.id,runId,test.spec.id,registration.token,test.spec.timeoutMs):prepareV2Workflow(test.source,test.spec,url+'/r/'+runId+'/'+test.spec.id,runId,test.spec.id,registration.token);r.sourceHash=prepared.sourceHash;r.analysisHash=sha256(JSON.stringify(analyzeWorkflow(test.source)));r.changes=prepared.changes;const deadline=AbortSignal.any([signal,AbortSignal.timeout(test.spec.timeoutMs)]);handle=await adapter.importWorkflow(prepared,runId,test.spec.id,deadline);r.cleanup.workflowId=handle.workflowId;await adapter.activate(handle,deadline);const marker=randomUUID(),trigger=await adapter.trigger(handle,test.input,marker,deadline);const execution=await adapter.observe(handle,marker,deadline);await gateway.drain(runId,test.spec.id);const capture=await gateway.snapshot(runId,test.spec.id);r.evidence={execution,requests:capture.requests,gatewayErrors:capture.errors,modelCalls:capture.modelCalls??[],...(trigger?{trigger}:{}),...(test.spec.tables.length?{tables:await adapter.tables?.(handle,deadline)}:{})};if(test.llm?.record&&test.modelConfig?.selection&&test.modelConfig.policy.mode==='local'){const calls=(capture.modelCalls??[]).filter(c=>c.status==='success'&&c.responseHash&&c.response);await writeRecording(test.llm.record,{formatVersion:1,protocol:'openai-chat',sourceHash:prepared.sourceHash,fixtureHash:test.input.sha256,selection:test.modelConfig.selection,settings:test.llm.settings,calls:calls.map(c=>({requestHash:c.requestHash,responseHash:c.responseHash!,response:c.response}))});}
 r.assertions=evaluate(test.spec.assertions as any,r.evidence);r.status=r.assertions.every(a=>a.passed)?'passed':'failed';
 }catch(error){r.error={code:error instanceof HarnessError?error.code:'INFRASTRUCTURE',message:redactor.text(errorMessage(error))};halted=true;}
 finally{try{await gateway.seal(runId,test.spec.id);}catch(error){r.status='error';r.error={code:'GATEWAY',message:redactor.text(errorMessage(error))};halted=true;}try{if(handle)await adapter.cleanup(handle);else await adapter.recover?.(test.spec.id);r.cleanup.status='cleaned';}catch(error){r.status='error';r.cleanup.status='failed';r.error={code:'CLEANUP',message:redactor.text(errorMessage(error))};halted=true;}try{await gateway.seal(runId,test.spec.id);if(r.evidence){const capture=await gateway.snapshot(runId,test.spec.id);r.evidence.requests=capture.requests;r.evidence.gatewayErrors=capture.errors;r.evidence.modelCalls=capture.modelCalls??[];r.assertions=evaluate(test.spec.assertions as any,r.evidence);if(r.status!=='error')r.status=r.assertions.every(a=>a.passed)?'passed':'failed';}}catch(error){if(r.evidence){r.status='error';r.error={code:'EVIDENCE',message:redactor.text(errorMessage(error))};halted=true;}}r.durationMs=Date.now()-began;results.push(r);onResult?.(r);}
 }
 for(const r of results)if(r.evidence){try{await gateway.drain(runId,r.id);const capture=await gateway.snapshot(runId,r.id);r.evidence.requests=capture.requests;r.evidence.gatewayErrors=capture.errors;r.evidence.modelCalls=capture.modelCalls??[];r.assertions=evaluate(compiled.find(t=>t.spec.id===r.id)!.spec.assertions as any,r.evidence);if(r.status!=='error')r.status=r.assertions.every(a=>a.passed)?'passed':'failed';}catch(error){r.status='error';r.error={code:'EVIDENCE',message:redactor.text(errorMessage(error))};}}
 return {schemaVersion:2,...(runtime?{runtime}:{}),runId,suite:suite.name,startedAt:new Date(start).toISOString(),durationMs:Date.now()-start,plannedExecutions:compiled.length,tests:results,exitCode:results.some(r=>r.status==='error')?2:results.some(r=>r.status==='failed')?1:0};
}
