import {it,expect,afterEach} from 'vitest';
import {mkdtemp,readFile,stat,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {ResourceJournal} from '../src/runtime/journal.js';
const dirs:string[]=[];afterEach(async()=>{for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});});
async function journal(){const d=await mkdtemp(join(tmpdir(),'journal-'));dirs.push(d);return new ResourceJournal(d,'run','https://fake.test');}
it('journals intent before create and confirms exact identity privately',async()=>{const j=await journal();const e=await j.begin({runId:'run',kind:'table',name:'exact',ownerIdentity:j.ownerIdentity});expect(JSON.parse(await readFile(j.path,'utf8')).entries[0]).toEqual(e);expect(e.state).toBe('creating');expect((await stat(j.path)).mode&0o777).toBe(0o600);await j.confirm(e.intentId,'123');expect((await ResourceJournal.load(j.path)).leftovers()[0]?.id).toBe('123');});
it('serializes mutations without losing an independent intent',async()=>{const j=await journal();await Promise.all(['table','credential'].map(kind=>j.begin({runId:'run',kind:kind as any,name:kind,ownerIdentity:j.ownerIdentity})));expect((await ResourceJournal.load(j.path)).leftovers()).toHaveLength(2);await expect(j.begin({runId:'other',kind:'table',name:'x',ownerIdentity:j.ownerIdentity})).rejects.toThrow(/identity/);});
it('failed save retains the recovery intent and never grants unknown ownership',async()=>{const j=await journal();const e=await j.begin({runId:'run',kind:'table',name:'x',ownerIdentity:j.ownerIdentity});await rm(j.directory,{recursive:true});await import('node:fs/promises').then(f=>f.writeFile(j.directory,'blocked'));await expect(j.confirm(e.intentId,'id')).rejects.toThrow();expect(j.leftovers()[0]?.id).toBe('id');await expect(j.confirm('unrecorded','id')).rejects.toThrow(/intent/);});
it('loads legacy manifests without granting ownership to unrelated resources',async()=>{const j=await journal();await import('node:fs/promises').then(f=>f.writeFile(j.path,JSON.stringify({schemaVersion:1,runId:'run',baseUrl:j.ownerIdentity,entries:[{runId:'run',testId:'one',name:'exact',workflowId:'123',executionIds:['9'],state:'owned'}]})));const loaded=await ResourceJournal.load(j.path);expect(loaded.leftovers().map(e=>[e.kind,e.id,e.parentId])).toEqual([['workflow','123',undefined],['execution','9','123']]);});
it('records definite rejection separately from an uncertain execution create',async()=>{const j=await journal(),e=await j.begin({runId:'run',kind:'execution',name:'marker',parentId:'wf',ownerIdentity:j.ownerIdentity});await j.cancelRejectedExecution(e.intentId);expect(j.leftovers()).toEqual([]);const other=await j.begin({runId:'run',kind:'workflow',name:'workflow',ownerIdentity:j.ownerIdentity});await expect(j.cancelRejectedExecution(other.intentId)).rejects.toThrow(/execution/);});
it('a stale recovery snapshot cannot erase ownership added by another journal instance',async()=>{const active=await journal();const wf=await active.begin({runId:'run',ownerIdentity:active.ownerIdentity,kind:'workflow',name:'workflow'});await active.confirm(wf.intentId,'wf');const recovery=await ResourceJournal.load(active.path);const table=await active.begin({runId:'run',ownerIdentity:active.ownerIdentity,kind:'table',name:'table'});await active.confirm(table.intentId,'table');await expect(recovery.markCleaned(wf.intentId)).rejects.toThrow(/changed|stale|reload/);expect((await ResourceJournal.load(active.path)).leftovers().map(e=>e.id)).toEqual(['wf','table']);});
