import {requireActive} from '../../runtime/cancellation.js';
import type {CloudClient} from '../n8n-cloud/client.js';import type {PreparedWorkflow,TableEvidence} from '../../runtime/types.js';import type {LogicalTable} from '../../spec/normalized.js';import {ResourceJournal,type OwnedRecord} from '../../runtime/journal.js';import {createOwned} from './resources.js';import {HarnessError} from '../../security/errors.js';
export interface OwnedTable {tableId:string;resourceId:string;intent:OwnedRecord;}
export function validateTable(t:LogicalTable){for(const c of t.columns)if(['id','createdAt','updatedAt','__proto__','constructor','prototype'].includes(c.name))throw new HarnessError('CONFIG','Reserved table column');for(const row of t.seedRows)for(const[k,v]of Object.entries(row)){const c=t.columns.find(c=>c.name===k);if(!c||v!==null&&typeof v!==c.type)throw new HarnessError('CONFIG','Seed row does not match declared column types');}}
export async function createTables(client:Pick<CloudClient,'request'>,journal:ResourceJournal,prepared:PreparedWorkflow,testId:string,parentId?:string,signal?:AbortSignal):Promise<OwnedTable[]>{const resources=prepared.resources;if(!resources)return [];const result:OwnedTable[]=[];for(const table of resources.tables){requireActive(signal);validateTable(table);const name=prepared.workflow.name+'-table-'+table.id;const intent=await createOwned(journal,{kind:'table',name,testId,parentId},()=>{requireActive(signal);return client.request('data-tables','POST',{name,columns:table.columns},signal);});result.push({tableId:table.id,resourceId:intent.id!,intent});requireActive(signal);if(table.seedRows.length)await client.request('data-tables/'+encodeURIComponent(intent.id!)+'/rows','POST',{data:table.seedRows,returnType:'all'},signal);}
 for(const binding of resources.bindings){requireActive(signal);const n=prepared.workflow.nodes.find(n=>n.id===binding.nodeId),table=result.find(t=>t.tableId===binding.tableId);if(!n||!table||n.parameters.dataTableId?.value!==binding.expectedResourceId&&n.parameters.dataTableId!==binding.expectedResourceId)throw new HarnessError('OWNERSHIP','Table binding differs from source');let id=table.resourceId;
 if(binding.fault){const schema=resources.tables.find(t=>t.id===binding.tableId)!;const name=prepared.workflow.name+'-fault-'+binding.nodeId;const fault=await createOwned(journal,{kind:'table',name,testId,parentId},()=>{requireActive(signal);return client.request('data-tables','POST',{name,columns:schema.columns},signal);});requireActive(signal);const raw=await client.request('data-tables/'+encodeURIComponent(fault.id!),'GET',undefined,signal);if(raw.name!==name)throw new HarnessError('OWNERSHIP','Fault table ownership changed');requireActive(signal);await client.request('data-tables/'+encodeURIComponent(fault.id!),'DELETE',undefined,signal);await journal.markCleaned(fault.intentId);id=fault.id!;}
 n.parameters.dataTableId={__rl:true,value:id,mode:'id'};prepared.changes.push(`Table ${n.id}: owned logical binding ${binding.tableId}${binding.fault?' with confirmed missing-table fault':''}`);
 }return result;
}
export async function collectTables(client:Pick<CloudClient,'request'>,journal:ResourceJournal,tables:OwnedTable[],signal:AbortSignal):Promise<TableEvidence[]>{const result:TableEvidence[]=[];for(const table of tables){const entry=journal.leftovers().find(e=>e.intentId===table.intent.intentId&&e.id===table.resourceId&&e.kind==='table'&&e.state==='owned');if(!entry)throw new HarnessError('OWNERSHIP','Table evidence requires exact owned identity');const raw=await client.request('data-tables/'+encodeURIComponent(table.resourceId)+'/rows?limit=100','GET',undefined,signal);if(!Array.isArray(raw?.data)||raw.data.length>100||raw.nextCursor||raw.data.some((r:any)=>!r||typeof r!=='object'||Array.isArray(r)))throw new HarnessError('EVIDENCE','Table evidence is missing, incomplete or exceeds row limits');result.push({tableId:table.tableId,resourceId:table.resourceId,rows:raw.data,complete:true,capturedAt:new Date().toISOString()});}return result;}
