import {GeneratedEnvironment} from './environment.js';
import {spawn} from 'node:child_process';import {HarnessError} from '../../security/errors.js';import type {OwnedRecord} from '../../runtime/journal.js';
export interface ContainerOptions {name:string;image:string;runId:string;network:string;publish?:boolean;volume?:string;envFile?:GeneratedEnvironment;readOnly?:boolean;cache?:boolean;command?:string[];cpus?:number;memory?:string;}
export function containerArguments(o:ContainerOptions):string[]{
 if(!/^(?:[A-Za-z0-9._/-]+@)?sha256:[a-f0-9]{64}$/.test(o.image)||Object.keys(o).some(k=>!['name','image','runId','network','publish','volume','envFile','readOnly','cache','command','cpus','memory'].includes(k)))throw new HarnessError('CONFIG','Only pinned images and scoped container options are allowed');
 for(const v of [o.name,o.runId,o.network,o.volume].filter(Boolean))if(!/^[A-Za-z0-9_-]{1,128}$/.test(v!))throw new HarnessError('CONFIG','Invalid Docker resource identity');
 if(o.envFile&&(!(o.envFile instanceof GeneratedEnvironment)||o.envFile.runId!==o.runId))throw new HarnessError('CONFIG','Host secret files cannot be mounted into workloads');
 return ['create','--name',o.name,'--label',`wfcheck.run=${o.runId}`,'--network',o.network,'--cap-drop=ALL','--security-opt','no-new-privileges:true','--cpus',String(o.cpus??2),'--memory',o.memory??'2g',...(o.envFile?['--env-file',o.envFile.path]:[]),...(o.readOnly?['--read-only','--tmpfs','/tmp:nosuid,nodev,noexec,size=128m']:[]),...(o.cache?['--tmpfs','/home/node/.cache:nosuid,nodev,noexec,size=128m,uid=1000,gid=1000,mode=700']:[]),...(o.publish?['-p','127.0.0.1::5678']:[]),...(o.volume?['--mount',`type=volume,source=${o.volume},target=/home/node/.n8n`]:[]),o.image,...(o.command??[])];
}
export async function spawnDocker(args:string[],signal?:AbortSignal,input?:string|Uint8Array):Promise<string>{
 return new Promise((resolve,reject)=>{const child=spawn('docker',args,{shell:false,stdio:['pipe','pipe','pipe'],signal});let length=0;const chunks:Buffer[]=[];child.stdout.on('data',b=>{length+=b.length;if(length>16*1024*1024){child.kill();reject(new HarnessError('DOCKER','Docker output exceeded limit'));}else chunks.push(b);});child.stderr.on('data',()=>{});child.on('error',()=>reject(new HarnessError('DOCKER','Docker command failed to start or was interrupted')));child.on('close',code=>code===0?resolve(Buffer.concat(chunks).toString('utf8').trim()):reject(new HarnessError('DOCKER',`Docker ${args[0]} failed with exit ${code}; workload stderr is withheld`)));child.stdin.on('error',()=>{});child.stdin.end(input);});
}
export class DockerEngine {
 constructor(private execute:(args:string[],signal?:AbortSignal,input?:string|Uint8Array)=>Promise<string>=spawnDocker){}
 exec(args:string[],signal?:AbortSignal,input?:string|Uint8Array){return this.execute(args,signal,input);}
 async identity(){const info=JSON.parse(await this.exec(['info','--format','{{json .}}']));if(typeof info.ID!=='string'||info.OSType!=='linux')throw new HarnessError('DOCKER','A Linux Docker daemon with a stable identity is required');return 'docker:'+info.ID;}
 async architecture(){const a=await this.exec(['info','--format','{{.Architecture}}']);if(['aarch64','arm64'].includes(a))return 'arm64';if(['x86_64','amd64'].includes(a))return 'amd64';throw new HarnessError('DOCKER','Unsupported Docker architecture');}
 async remove(e:OwnedRecord){if(e.ownerIdentity!==await this.identity())throw new HarnessError('OWNERSHIP','Docker daemon identity changed');let raw:any;try{raw=JSON.parse(await this.exec([...(e.kind==='container'?['inspect']:[e.kind,'inspect']),e.id!]));}catch{const list=await this.exec(e.kind==='container'?['ps','-a','-q','--no-trunc']:e.kind==='network'?['network','ls','-q','--no-trunc']:['volume','ls','-q']);if(list.split('\n').includes(e.id!))throw new HarnessError('CLEANUP','Exact Docker resource inspection failed');return;}
 const r=raw[0];const name=e.kind==='container'?r.Name?.replace(/^\//,''):r.Name;if(name!==e.name)throw new HarnessError('OWNERSHIP','Docker exact name changed');const labels=e.kind==='container'?r.Config?.Labels:r.Labels;if(labels?.['wfcheck.run']!==e.runId)throw new HarnessError('OWNERSHIP','Docker ownership label changed');await this.exec([e.kind==='container'?'rm':e.kind,...(e.kind==='container'?['-f']:['rm']),e.id!]);}
}
