import {reconcileDisposedState} from './disposal.js';
import {DockerEngine} from './engine.js';import {ResourceJournal} from '../../runtime/journal.js';import {recoverOwned} from '../n8n-api/resources.js';import {InternalApiClient} from './bootstrap.js';import {N8nApiAdapter} from '../n8n-api/index.js';import {Manifest} from '../../runtime/manifest.js';import {HarnessError,errorMessage} from '../../security/errors.js';import {randomUUID} from 'node:crypto';
export async function recoverDocker(journal:ResourceJournal){const engine=new DockerEngine(),owner=await engine.identity();if(journal.ownerIdentity!==owner)throw new HarnessError('OWNERSHIP','Docker daemon identity changed');const server=journal.leftovers().find(e=>e.kind==='container'&&e.name.endsWith('-n8n'));let adapter:N8nApiAdapter|undefined;
 const setupErrors:string[]=[];if(server?.id)try{const raw=JSON.parse(await engine.exec(['inspect',server.id!]));if(raw[0]?.Name!=='/'+server.name||raw[0]?.Config?.Labels?.['wfcheck.run']!==journal.runId)throw new HarnessError('OWNERSHIP','Recovery n8n container identity changed');if(!raw[0].State.Running)await engine.exec(['start',server.id!]);const keyScript=String.raw`(async()=>{const fs=require('fs'),ff=require('fflate'),{Cipher}=require('n8n-core');const key=fs.readFileSync('/home/node/.n8n/seed-key','utf8'),cipher=new Cipher({encryptionKey:key},{}),zip=ff.unzipSync(fs.readFileSync('/home/node/.n8n/seed/entities.zip'));const line=await cipher.decryptV2(Buffer.from(zip['apikey.jsonl']).toString(),key);const record=JSON.parse(line);process.stdout.write(record.apiKey);})().catch(()=>process.exit(1));`;
 const key=await engine.exec(['exec','-w','/usr/local/lib/node_modules/n8n',server.id!,'node','-e',keyScript]);const client=new InternalApiClient(engine,server.id!,key);
 adapter=new N8nApiAdapter(client as any,new Manifest(journal.directory,journal.runId,client.baseUrl),journal,{managedDocker:true,credentialReader:async id=>{const file='/home/node/.n8n/credential-check-'+randomUUID()+'.json';await engine.exec(['exec',server.id!,'n8n','export:credentials','--id='+id,'--output='+file]);return JSON.parse(await engine.exec(['exec','-i',server.id!,'node','-e',"const fs=require('fs'),file=JSON.parse(fs.readFileSync(0,'utf8')).file;try{const r=JSON.parse(fs.readFileSync(file));if(r.length!==1)throw Error();console.log(JSON.stringify({id:r[0].id,name:r[0].name}));}finally{fs.unlinkSync(file);}"],undefined,JSON.stringify({file})));}});
 }catch(error){setupErrors.push('API recovery unavailable: '+errorMessage(error));}
 const result=await recoverOwned(journal,owner,{remove:async e=>{if(['workflow','execution','credential','table'].includes(e.kind)){if(!adapter)throw new HarnessError('CLEANUP','Owned n8n instance is unavailable for exact API resource recovery');await adapter.removeResource(e);}else await engine.remove(e);}});await reconcileDisposedState(journal,engine);return {errors:[...setupErrors,...result.errors],leftovers:journal.leftovers()};
}
