import {z} from 'zod';import {assertionV2Schema} from '../spec/schema-v2.js';import type {Provenance} from '../analysis/types.js';import type {DraftPlan} from './types.js';import {assistantProjection,assistantSystem,type AssistantInput} from './prompt.js';import type {ModelSelection} from '../llm/types.js';import {chat} from '../llm/client.js';import {sha256} from '../spec/load.js';import {HarnessError} from '../security/errors.js';
const id=z.string().regex(/^[A-Za-z0-9_-]{1,64}$/);const proposal=z.discriminatedUnion('kind',[
 z.strictObject({kind:z.literal('intent'),text:z.string().min(1).max(1000)}),
 z.strictObject({kind:z.literal('unresolved'),text:z.string().min(1).max(1000),nodeId:id.optional()}),
 z.strictObject({kind:z.literal('fixture'),nodeId:id,input:z.record(z.string(),z.json())}),
 z.strictObject({kind:z.literal('assertion'),fixtureId:id,assertion:assertionV2Schema})
]);
const proposals=z.array(proposal).max(20);export type PlanProposal=z.infer<typeof proposal>&{provenance:Provenance};
export function parseProposals(raw:string,provenance:Provenance):PlanProposal[]{if(Buffer.byteLength(raw)>65536)throw new HarnessError('LLM','Planning response exceeds limit');let value;try{value=JSON.parse(raw);}catch{throw new HarnessError('LLM','Invalid/truncated assistant JSON');}if(!Array.isArray(value))value=z.strictObject({proposals}).parse(value).proposals;return proposals.parse(value).map(p=>({...p,provenance:{...provenance,source:'inferred'}}));}
export function mergeProposals(draft:DraftPlan,suggestions:PlanProposal[]):DraftPlan{const ids=new Set(draft.analysis.nodes.map(n=>n.id));for(const p of suggestions){if('nodeId'in p&&p.nodeId&&!ids.has(p.nodeId)||p.kind==='assertion'&&'nodeId'in p.assertion&&!ids.has(p.assertion.nodeId))throw new HarnessError('CONFIG','Proposal refers to an unknown deterministic node');}return {...structuredClone(draft),suggestions};}
export async function assistPlan(draft:DraftPlan,input:AssistantInput,selection:ModelSelection,signal:AbortSignal):Promise<PlanProposal[]>{const projection=assistantProjection(draft,input),projectionHash=sha256(JSON.stringify(projection));const outputSchema={proposals:[{kind:'intent',text:'inferred purpose'},{kind:'unresolved',text:'missing configuration',nodeId:'existing-node-id'},{kind:'fixture',nodeId:'existing-node-id',input:{}},{kind:'assertion',fixtureId:'existing-test-id',assertion:{target:'execution.status',equals:'success'}}]};const call=await chat(selection,{messages:[{role:'system',content:assistantSystem+' Return at most four concise proposals. Assertion fixtureId must be one of '+JSON.stringify(draft.proposedSuite.tests.map(t=>t.id))+'. Allowed proposal shapes: '+JSON.stringify(outputSchema)},{role:'user',content:JSON.stringify(projection)}],responseFormat:{type:'json_schema',json_schema:{name:'workflow_test_proposals',strict:true,schema:{type:'object',required:['proposals'],additionalProperties:false,properties:{proposals:{type:'array',maxItems:4,items:{type:'object',required:['kind'],additionalProperties:false,properties:{kind:{type:'string',enum:['intent','unresolved','fixture','assertion']},text:{type:'string',minLength:1,maxLength:500},nodeId:{type:'string',enum:draft.analysis.nodes.map(n=>n.id)},fixtureId:{type:'string',enum:draft.proposedSuite.tests.map(t=>t.id)},input:{type:'object'},assertion:{type:'object'}}}}}}}}},{temperature:0,seed:0,maxOutputTokens:1024,contextTokens:8192,timeoutMs:60000,...(selection.supportsNoThinking?{think:false as const}:{})},{purpose:'planning'},signal);if(call.status!=='success')throw new HarnessError('LLM',call.error?.message??'Assistant response unavailable');const text=(call.response as any)?.choices?.[0]?.message?.content;if(typeof text!=='string')throw new HarnessError('LLM','Assistant response lacks content');return parseProposals(text,{source:'inferred',artifactHash:projectionHash,note:'Model '+selection.model+' digest '+selection.digest});}
