import {prepareNativeChat} from './native-chat.js';
import {validateTableNode} from './table-node.js';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';import type {NormalizedTest} from '../spec/normalized.js';import {sha256} from '../spec/load.js';import {projectWorkflow} from '../analysis/export.js';import {analyzeWorkflow} from '../analysis/index.js';import {lookupCapability} from '../analysis/registry.js';import {legacyNodeDefinitions} from './workflow.js';import {HarnessError} from './errors.js';import type {PreparedWorkflow} from '../runtime/types.js';
const nodeKeys=new Set(['id','name','type','typeVersion','position','parameters','credentials','retryOnFail','maxTries','waitBetweenTries','onError','alwaysOutputData','webhookId','notes','notesInFlow','disabled']);
const nodeShape=z.object({id:z.string().regex(/^[A-Za-z0-9_-]{1,64}$/),name:z.string().min(1).max(128),type:z.string(),typeVersion:z.number(),position:z.tuple([z.number(),z.number()]),parameters:z.record(z.string(),z.unknown()),disabled:z.boolean().optional(),alwaysOutputData:z.boolean().optional(),retryOnFail:z.boolean().optional(),maxTries:z.int().min(1).max(3).optional(),waitBetweenTries:z.int().min(0).max(2000).optional(),onError:z.enum(['stopWorkflow','continueRegularOutput','continueErrorOutput']).optional()});
const pairs=z.strictObject({parameters:z.array(z.strictObject({name:z.string().regex(/^[A-Za-z0-9_-]{1,64}$/),value:z.union([z.string(),z.number(),z.boolean()])})).max(20)});
const http=z.strictObject({method:z.enum(['GET','HEAD','POST','PUT','PATCH','DELETE']),url:z.string().max(2048),authentication:z.enum(['none','genericCredentialType','predefinedCredentialType']).optional(),genericAuthType:z.literal('httpHeaderAuth').optional(),nodeCredentialType:z.literal('gmailOAuth2').optional(),sendQuery:z.boolean().optional(),queryParameters:pairs.optional(),sendBody:z.boolean().optional(),sendHeaders:z.boolean().optional(),headerParameters:pairs.optional(),contentType:z.literal('json').optional(),specifyBody:z.enum(['json','keypair']).optional(),jsonBody:z.union([z.string(),z.record(z.string(),z.json())]).optional(),bodyParameters:pairs.optional(),options:z.strictObject({timeout:z.int().min(100).max(120000).optional(),redirect:z.strictObject({redirect:z.strictObject({followRedirects:z.boolean(),maxRedirects:z.int().optional()})}).optional(),response:z.strictObject({response:z.strictObject({responseFormat:z.enum(['json','text']),fullResponse:z.boolean().optional(),neverError:z.boolean().optional()})}).optional()})});
const code=z.strictObject({mode:z.literal('runOnceForAllItems'),jsCode:z.string().min(1).max(262144).refine(value=>Buffer.byteLength(value)<=262144,'Code exceeds 256 KiB UTF-8 limit')});
const pdf=z.strictObject({operation:z.literal('pdf'),binaryPropertyName:z.string().regex(/^[A-Za-z0-9_-]{1,64}$/),options:z.strictObject({maxPages:z.int().min(1).max(10).optional(),joinPages:z.boolean().optional(),keepSource:z.enum(['json','binary','both']).optional()})});
const form=z.strictObject({authentication:z.enum(['none','basicAuth']).optional(),path:z.string().max(256).optional(),formTitle:z.string().max(256),formDescription:z.string().max(4096).optional(),formFields:z.strictObject({values:z.array(z.strictObject({fieldLabel:z.string().regex(/^[A-Za-z0-9_-]{1,64}$/),fieldType:z.literal('file'),requiredField:z.boolean().optional(),multipleFiles:z.boolean().optional(),acceptFileTypes:z.string().max(256).optional()})).length(1)}),responseMode:z.enum(['onReceived','lastNode']),options:z.strictObject({path:z.string().max(256).optional(),appendAttribution:z.boolean().optional(),respondWithOptions:z.strictObject({values:z.strictObject({respondWith:z.literal('text').optional(),responseBody:z.string().max(4096).optional(),formSubmittedText:z.string().max(4096).optional()})}).optional()})});
export function prepareV2Workflow(source:string,test:NormalizedTest,gatewayUrl:string,runId:string,testId:string,token:string):PreparedWorkflow{
 const wf=projectWorkflow(source),hash=sha256(source),analysis=analyzeWorkflow(source);if(wf.nodes.length>200)throw new HarnessError('UNSUPPORTED','Execution supports at most 200 nodes');if(test.trust&&test.trust.sourceHash!==hash)throw new HarnessError('CONFIG','Reviewed source hash changed');
 if(analysis.diagnostics.some(d=>d.severity==='error'))throw new HarnessError('UNSUPPORTED','Invalid or unsupported workflow graph: '+analysis.diagnostics.filter(d=>d.severity==='error').map(d=>d.code).join(', '));
 if(analysis.edges.some(e=>!['main','ai_languageModel'].includes(e.connectionType)||e.inputIndex!==0||e.outputIndex>1))throw new HarnessError('UNSUPPORTED','Unqualified connection type or main port');
 for(const e of analysis.edges.filter(e=>e.connectionType==='ai_languageModel'))if(wf.nodes.find(n=>n.id===e.from)?.type!=='@n8n/n8n-nodes-langchain.lmChatOpenAi'||wf.nodes.find(n=>n.id===e.to)?.type!=='@n8n/n8n-nodes-langchain.chainLlm')throw new HarnessError('UNSUPPORTED','Unqualified AI model connection');for(const n of wf.nodes.filter(n=>n.type==='@n8n/n8n-nodes-langchain.chainLlm'))if(analysis.edges.filter(e=>e.to===n.id&&e.connectionType==='ai_languageModel').length!==1)throw new HarnessError('UNSUPPORTED','Chain needs exactly one qualified AI model');
 const selected=test.triggerId??(analysis.triggers.length===1?analysis.triggers[0]!.nodeId:undefined);if(!selected||!analysis.triggers.some(t=>t.nodeId===selected))throw new HarnessError('UNSUPPORTED','Exactly one supported intake trigger must be explicitly selected');
 const changes=['name: unique project-owned copy','settings: save complete execution data with bounded timeout'];const copy=structuredClone(wf);copy.name=`wfcheck-dev-${runId}-${testId}`;copy.settings={saveDataSuccessExecution:'all',saveDataErrorExecution:'all',saveExecutionProgress:true,saveManualExecutions:true,executionTimeout:Math.ceil(test.timeoutMs/1000),executionOrder:'v1'};
 const usedHttp=new Set<string>(),usedTables=new Set<string>(),usedMocks=new Set<string>(),usedChildren=new Set<string>();
 for(const n of copy.nodes){nodeShape.parse(n);
  if(Object.keys(n).some(k=>!nodeKeys.has(k)))throw new HarnessError('UNSUPPORTED','Unknown runtime node field');const capability=lookupCapability(n.type,n.typeVersion,n.parameters.operation??n.parameters.method);if(!capability||!capability.executable)throw new HarnessError('UNSUPPORTED','Node adapter is not qualified: '+n.id);
  if(n.retryOnFail&&(!['n8n-nodes-base.httpRequest','n8n-nodes-base.dataTable'].includes(n.type)||!Number.isInteger(n.maxTries)||n.maxTries!<1||n.maxTries!>3||!Number.isInteger(n.waitBetweenTries)||n.waitBetweenTries!<0||n.waitBetweenTries!>2000))throw new HarnessError('UNSUPPORTED','Retries must be explicit bounded HTTP retries');
  if(n.onError&&!['stopWorkflow','continueRegularOutput','continueErrorOutput'].includes(n.onError))throw new HarnessError('UNSUPPORTED','Unsupported error behavior');
  const creds=n.credentials??{};if(!creds||typeof creds!=='object'||Array.isArray(creds)||Object.keys(creds as object).some(k=>!(['n8n-nodes-base.httpRequest'].includes(n.type)?['httpHeaderAuth','gmailOAuth2']:n.type==='@n8n/n8n-nodes-langchain.lmChatOpenAi'?['openAiApi']:n.type==='n8n-nodes-base.gmail'?['gmailOAuth2']:['n8n-nodes-base.formTrigger','n8n-nodes-base.webhook'].includes(n.type)?['httpBasicAuth','httpHeaderAuth']:[]).includes(k)))throw new HarnessError('UNSUPPORTED','Unknown or misplaced credential type');delete n.credentials;
  if(n.type.startsWith('@n8n/n8n-nodes-langchain.')){prepareNativeChat(n,gatewayUrl,test.timeoutMs);changes.push(`Native chat ${n.id}: isolated non-streaming completion transport`);}
  else if(n.type==='n8n-nodes-base.code'){code.parse(n.parameters);if(test.trust?.sourceHash!==hash||!test.trust.reviewedCode.some(c=>c.nodeId===n.id&&c.codeHash===sha256(n.parameters.jsCode)&&c.noExternalEffects))throw new HarnessError('CONFIG','Code hash/effects need exact authored review');}
  else if(n.type==='n8n-nodes-base.gmail'){
   z.strictObject({resource:z.literal('message'),operation:z.literal('send'),sendTo:z.string(),subject:z.string(),emailType:z.literal('text'),message:z.string(),options:z.strictObject({appendAttribution:z.boolean().optional()})}).parse(n.parameters);
   const binding=test.nodeMocks.find(b=>b.nodeId===n.id);if(!binding||binding.expectedParametersHash!==sha256(JSON.stringify(n.parameters)))throw new HarnessError('CONFIG','Gmail delivery boundary needs an exact authored parameters pin');
   const p=n.parameters;n.type='n8n-nodes-base.httpRequest';n.typeVersion=4.2;n.parameters={method:'POST',url:gatewayUrl+binding.mockPath,authentication:'none',sendBody:true,contentType:'json',specifyBody:'keypair',bodyParameters:{parameters:[{name:'sendTo',value:p.sendTo},{name:'subject',value:p.subject},{name:'message',value:p.message}]},sendHeaders:true,headerParameters:{parameters:[{name:'x-wfcheck-token',value:token}]},options:{timeout:10000,redirect:{redirect:{followRedirects:false,maxRedirects:0}}}};usedMocks.add(n.id);changes.push(`Gmail ${n.id}: synthetic HTTP delivery boundary; native Gmail transport is not exercised`);
  }
  else if(n.type==='n8n-nodes-base.executeWorkflow'){
   z.strictObject({source:z.literal('database'),workflowId:z.strictObject({__rl:z.literal(true),mode:z.literal('id'),value:z.string()}),mode:z.literal('once'),options:z.strictObject({waitForSubWorkflow:z.literal(true)}),workflowInputs:z.strictObject({mappingMode:z.literal('passThrough'),value:z.strictObject({}),matchingColumns:z.array(z.string()).length(0),schema:z.array(z.unknown()).length(0),attemptToConvertTypes:z.literal(false),convertFieldsToString:z.literal(false)})}).parse(n.parameters);
   const binding=test.subworkflows.find(b=>b.nodeId===n.id);if(!binding||binding.expectedWorkflowId!==n.parameters.workflowId.value)throw new HarnessError('CONFIG','Exact isolated child workflow binding is required');usedChildren.add(n.id);
  }
  else if(n.type==='n8n-nodes-base.scheduleTrigger'){z.strictObject({rule:z.strictObject({interval:z.array(z.strictObject({field:z.literal('cronExpression'),expression:z.string().max(128)})).min(1).max(5)})}).parse(n.parameters);n.disabled=true;changes.push(`Schedule ${n.id}: disabled in isolated test copy`);}
  else if(n.type==='n8n-nodes-base.executeWorkflowTrigger'){z.strictObject({inputSource:z.literal('passthrough')}).parse(n.parameters);}
  else if(n.type==='n8n-nodes-base.webhook'){z.strictObject({httpMethod:z.literal('POST'),path:z.string().max(256),authentication:z.enum(['none','headerAuth','basicAuth']).optional(),responseMode:z.enum(['onReceived','lastNode']),options:z.strictObject({})}).parse(n.parameters);n.parameters.authentication='none';if(n.id!==selected)n.disabled=true;changes.push(`Webhook ${n.id}: disposable capability path replaces source authentication`);}
  else if(n.type==='n8n-nodes-base.extractFromFile')pdf.parse(n.parameters);
  else if(n.type==='n8n-nodes-base.formTrigger'){form.parse(n.parameters);if(n.id!==selected)n.disabled=true;if(n.id===selected&&(test.input.kind!=='file'||n.parameters.formFields.values[0].fieldLabel!==test.input.field||n.parameters.formFields.values[0].multipleFiles===true))throw new HarnessError('CONFIG','File input must match the single Form field');n.parameters.authentication='basicAuth';n.parameters.formFields.values[0].multipleFiles=false;changes.push(`Form ${n.id}: disposable Basic authentication and one-file input`);}
  else if(n.type==='n8n-nodes-base.httpRequest'){
   http.parse(n.parameters);const binding=test.bindings.find(b=>b.nodeId===n.id),url=n.parameters.url;
   if(url.startsWith('{{WFCHECK_GATEWAY}}/'))n.parameters.url=url.replace('{{WFCHECK_GATEWAY}}',gatewayUrl);
   else{if(!binding||binding.expectedUrl!==url)throw new HarnessError('CONFIG','Exact HTTP binding is required');if(!url.startsWith('=')&&!url.includes('{{')){const original=new URL(url);if(!['https:','http:'].includes(original.protocol)||original.username||original.password)throw new HarnessError('UNSUPPORTED','Unsafe HTTP destination');}else if(test.trust?.sourceHash!==hash||!test.trust.reviewedExpressions)throw new HarnessError('CONFIG','Dynamic HTTP binding needs exact authored expressions review');n.parameters.url=gatewayUrl+binding.mockPath;usedHttp.add(n.id);}
   for(const h of n.parameters.headerParameters?.parameters??[])if(!(/^x-fake-[a-z0-9-]+$|^x-api-key$/.test(h.name)&&typeof h.value==='string'&&h.value.startsWith('fake-')||binding&&/^(Accept|User-Agent)$/i.test(h.name)&&typeof h.value==='string'&&!h.value.includes('{{')))throw new HarnessError('UNSUPPORTED','Only fake literal test headers may be copied');
   n.parameters.authentication='none';delete n.parameters.genericAuthType;delete n.parameters.nodeCredentialType;n.parameters.sendHeaders=true;n.parameters.headerParameters??={parameters:[]};n.parameters.headerParameters.parameters.push({name:'x-wfcheck-token',value:token});n.parameters.options.timeout=Math.min(n.parameters.options.timeout??10000,test.timeoutMs,60000);n.parameters.options.redirect={redirect:{followRedirects:false,maxRedirects:0}};changes.push(`HTTP ${n.id}: isolated binding, disposable authentication, bounded timeout and disabled redirects`);
  }else if(n.type==='n8n-nodes-base.dataTable'){const binding=test.tableBindings.find(b=>b.nodeId===n.id),original=typeof n.parameters.dataTableId==='string'?n.parameters.dataTableId:n.parameters.dataTableId?.value;if(!binding||binding.expectedResourceId!==original)throw new HarnessError('CONFIG','Exact table binding is required');const table=test.tables.find(t=>t.id===binding.tableId);if(!table)throw new HarnessError('CONFIG','Table schema is missing');validateTableNode(n.parameters,table);usedTables.add(n.id);}
  else legacyNodeDefinitions[n.type]!.params.parse(n.parameters);
  const inspect=(value:unknown,key='')=>{if(n.type==='n8n-nodes-base.code'&&key==='jsCode')return;if(typeof value==='string'&&(value.startsWith('=')||value.includes('{{'))&&!value.startsWith('{{WFCHECK_GATEWAY}}/')){if(!/^=\{\{\s*\$json(?:\.[A-Za-z_][A-Za-z0-9_]*)+(?:\s*\|\|\s*(?:""|''))?\s*\}\}$/.test(value))if(test.trust?.sourceHash!==hash||!test.trust.reviewedExpressions)throw new HarnessError('CONFIG','Nontrivial expressions need exact authored review');}else if(Array.isArray(value))value.forEach(v=>inspect(v));else if(value&&typeof value==='object')for(const[k,v]of Object.entries(value)){if(['__proto__','constructor','prototype'].includes(k))throw new HarnessError('UNSUPPORTED','Reserved parameter field');inspect(v,k);}};inspect(n.parameters);
 }
 if(test.nodeMocks.some(b=>!usedMocks.has(b.nodeId))||test.subworkflows.some(b=>!usedChildren.has(b.nodeId)))throw new HarnessError('CONFIG','Unused node mock or child workflow binding');
 if(test.bindings.some(b=>!usedHttp.has(b.nodeId))||test.tableBindings.some(b=>!usedTables.has(b.nodeId)))throw new HarnessError('CONFIG','Binding references an unknown or mismatched node');
 const trigger=copy.nodes.find(n=>n.id===selected)!;if(trigger.type==='n8n-nodes-base.webhook'&&test.input.kind!=='json')throw new HarnessError('CONFIG','Webhook requires JSON input');trigger.parameters.path=`wfcheck-${runId}-${testId}-${token.slice(0,24)}`;if(trigger.type==='n8n-nodes-base.formTrigger'){trigger.parameters.options.path=trigger.parameters.path;delete trigger.parameters.path;trigger.webhookId=randomUUID();}else delete trigger.webhookId;changes.push(`Trigger ${trigger.id}: unique correlation capability path`);
 const descriptor={kind:trigger.type==='n8n-nodes-base.formTrigger'?'form-file' as const:'webhook-json' as const,nodeId:trigger.id,nodeName:trigger.name,path:trigger.parameters.options.path??trigger.parameters.path,...(test.input.kind==='file'?{fileField:test.input.field,transportField:'field-0'}:{})};
 return {modelToken:token,workflow:copy,sourceHash:hash,changes,webhookNodeId:trigger.id,webhookNodeName:trigger.name,webhookPath:descriptor.path,trigger:descriptor,resources:{tables:structuredClone(test.tables),bindings:structuredClone(test.tableBindings)}};
}
